#pragma once

#include <kernel/Keyboard.h>

namespace Keyboard {

static Key scs2_to_key_shift[0xFF] = {
    Key::INVALID,
    Key::F9,
    Key::INVALID,
    Key::F5,
    Key::F3,
    Key::F1,
    Key::F2,
    Key::F12,
    Key::INVALID,
    Key::F10,
    Key::F8,
    Key::F6,
    Key::F4,
    Key::Tab,
    Key::Tilde,
    Key::INVALID,
    Key::INVALID,
    Key::Alt,
    Key::LeftShift,
    Key::INVALID,
    Key::Ctrl,
    Key::Q,
    Key::ExclamationMark,
    Key::INVALID,
    Key::INVALID,
    Key::INVALID,
    Key::Z,
    Key::S,
    Key::A,
    Key::W,
    Key::At,
    Key::INVALID,
    Key::INVALID,
    Key::C,
    Key::X,
    Key::D,
    Key::E,
    Key::Dollar,
    Key::Hashtag,
    Key::INVALID,
    Key::INVALID,
    Key::Space,
    Key::V,
    Key::F,
    Key::T,
    Key::R,
    Key::Percent,
    Key::INVALID,
    Key::INVALID,
    Key::N,
    Key::B,
    Key::H,
    Key::G,
    Key::Y,
    Key::Caret,
    Key::INVALID,
    Key::INVALID,
    Key::INVALID,
    Key::M,
    Key::J,
    Key::U,
    Key::Ampersand,
    Key::Asterisk,
    Key::INVALID,
    Key::INVALID,
    Key::LessThan,
    Key::K,
    Key::I,
    Key::O,
    Key::CloseParen,
    Key::OpenParen,
    Key::INVALID,
    Key::INVALID,
    Key::MoreThan,
    Key::QuestionMark,
    Key::L,
    Key::Colon,
    Key::P,
    Key::Underscore,
    Key::INVALID,
    Key::INVALID,
    Key::INVALID,
    Key::DoubleQuote,
    Key::INVALID,
    Key::OpenBrace,
    Key::Plus,
    Key::INVALID,
    Key::INVALID,
    Key::CapsLock,
    Key::RightShift,
    Key::Enter,
    Key::CloseBrace,
    Key::INVALID,
    Key::Pipe,
    Key::INVALID,
    Key::INVALID,
    Key::INVALID,
    Key::INVALID,
    Key::INVALID,
    Key::INVALID,
    Key::INVALID,
    Key::INVALID,
    Key::Backspace,
    Key::INVALID,
    Key::INVALID,
    Key::Numpad1,
    Key::INVALID,
    Key::Numpad4,
    Key::Numpad7,
    Key::INVALID,
    Key::INVALID,
    Key::INVALID,
    Key::Numpad0,
    Key::NumpadComma,
    Key::Numpad2,
    Key::Numpad5,
    Key::Numpad6,
    Key::Numpad8,
    Key::Escape,
    Key::NumLock,
    Key::F11,
    Key::NumpadPlus,
    Key::Numpad3,
    Key::NumpadMinus,
    Key::NumpadMult,
    Key::Numpad9,
    Key::INVALID,
    Key::INVALID,
    Key::INVALID,
    Key::INVALID,
    Key::INVALID,
    Key::F7,
};

static Key scs2_to_key_altgr[0xFF] = {
    Key::INVALID,    Key::F9,          Key::INVALID,   Key::F5,
    Key::F3,         Key::F1,          Key::F2,        Key::F12,
    Key::INVALID,    Key::F10,         Key::F8,        Key::F6,
    Key::F4,         Key::Tab,         Key::INVALID,   Key::INVALID,
    Key::INVALID,    Key::Alt,         Key::LeftShift, Key::INVALID,
    Key::Ctrl,       Key::INVALID,     Key::INVALID,   Key::INVALID,
    Key::INVALID,    Key::INVALID,     Key::INVALID,   Key::INVALID,
    Key::INVALID,    Key::INVALID,     Key::INVALID,   Key::INVALID,
    Key::INVALID,    Key::INVALID,     Key::INVALID,   Key::INVALID,
    Key::Euro,       Key::INVALID,     Key::INVALID,   Key::INVALID,
    Key::INVALID,    Key::INVALID,     Key::INVALID,   Key::INVALID,
    Key::INVALID,    Key::INVALID,     Key::INVALID,   Key::INVALID,
    Key::INVALID,    Key::INVALID,     Key::INVALID,   Key::INVALID,
    Key::INVALID,    Key::INVALID,     Key::INVALID,   Key::INVALID,
    Key::INVALID,    Key::INVALID,     Key::INVALID,   Key::INVALID,
    Key::INVALID,    Key::INVALID,     Key::INVALID,   Key::INVALID,
    Key::INVALID,    Key::INVALID,     Key::INVALID,   Key::INVALID,
    Key::INVALID,    Key::INVALID,     Key::INVALID,   Key::INVALID,
    Key::INVALID,    Key::INVALID,     Key::INVALID,   Key::INVALID,
    Key::INVALID,    Key::INVALID,     Key::INVALID,   Key::INVALID,
    Key::INVALID,    Key::INVALID,     Key::INVALID,   Key::INVALID,
    Key::INVALID,    Key::INVALID,     Key::INVALID,   Key::INVALID,
    Key::CapsLock,   Key::RightShift,  Key::Enter,     Key::INVALID,
    Key::INVALID,    Key::INVALID,     Key::INVALID,   Key::INVALID,
    Key::INVALID,    Key::INVALID,     Key::INVALID,   Key::INVALID,
    Key::INVALID,    Key::INVALID,     Key::Backspace, Key::INVALID,
    Key::INVALID,    Key::Numpad1,     Key::INVALID,   Key::Numpad4,
    Key::Numpad7,    Key::INVALID,     Key::INVALID,   Key::INVALID,
    Key::Numpad0,    Key::NumpadComma, Key::Numpad2,   Key::Numpad5,
    Key::Numpad6,    Key::Numpad8,     Key::Escape,    Key::NumLock,
    Key::F11,        Key::NumpadPlus,  Key::Numpad3,   Key::NumpadMinus,
    Key::NumpadMult, Key::Numpad9,     Key::INVALID,   Key::INVALID,
    Key::INVALID,    Key::INVALID,     Key::INVALID,   Key::F7,
};

static Key scs2_to_key[0xFF] = {
    Key::INVALID,     Key::F9,          Key::INVALID,     Key::F5,
    Key::F3,          Key::F1,          Key::F2,          Key::F12,
    Key::INVALID,     Key::F10,         Key::F8,          Key::F6,
    Key::F4,          Key::Tab,         Key::BackTick,    Key::INVALID,
    Key::INVALID,     Key::Alt,         Key::LeftShift,   Key::INVALID,
    Key::Ctrl,        Key::Q,           Key::_1,          Key::INVALID,
    Key::INVALID,     Key::INVALID,     Key::Z,           Key::S,
    Key::A,           Key::W,           Key::_2,          Key::INVALID,
    Key::INVALID,     Key::C,           Key::X,           Key::D,
    Key::E,           Key::_4,          Key::_3,          Key::INVALID,
    Key::INVALID,     Key::Space,       Key::V,           Key::F,
    Key::T,           Key::R,           Key::_5,          Key::INVALID,
    Key::INVALID,     Key::N,           Key::B,           Key::H,
    Key::G,           Key::Y,           Key::_6,          Key::INVALID,
    Key::INVALID,     Key::INVALID,     Key::M,           Key::J,
    Key::U,           Key::_7,          Key::_8,          Key::INVALID,
    Key::INVALID,     Key::Comma,       Key::K,           Key::I,
    Key::O,           Key::_0,          Key::_9,          Key::INVALID,
    Key::INVALID,     Key::Period,      Key::Slash,       Key::L,
    Key::Semicolon,   Key::P,           Key::Hyphen,      Key::INVALID,
    Key::INVALID,     Key::INVALID,     Key::SingleQuote, Key::INVALID,
    Key::OpenBracket, Key::Equals,      Key::INVALID,     Key::INVALID,
    Key::CapsLock,    Key::RightShift,  Key::Enter,       Key::CloseBracket,
    Key::INVALID,     Key::BackSlash,   Key::INVALID,     Key::INVALID,
    Key::INVALID,     Key::INVALID,     Key::INVALID,     Key::INVALID,
    Key::INVALID,     Key::INVALID,     Key::Backspace,   Key::INVALID,
    Key::INVALID,     Key::Numpad1,     Key::INVALID,     Key::Numpad4,
    Key::Numpad7,     Key::INVALID,     Key::INVALID,     Key::INVALID,
    Key::Numpad0,     Key::NumpadComma, Key::Numpad2,     Key::Numpad5,
    Key::Numpad6,     Key::Numpad8,     Key::Escape,      Key::NumLock,
    Key::F11,         Key::NumpadPlus,  Key::Numpad3,     Key::NumpadMinus,
    Key::NumpadMult,  Key::Numpad9,     Key::INVALID,     Key::INVALID,
    Key::INVALID,     Key::INVALID,     Key::INVALID,     Key::F7,
};
} // namespace Keyboard